### ISSUE TITLE
操作日志starter 切面内引用数组List 导致添加方法报错 

### ISSUE THREAD

**Issue by xiaoashuo** [ballcat-projects/ballcat#107]
private final List<Class<?>> ignoredParamClasses = Arrays.asList(ServletRequest.class, ServletResponse.class,
			MultipartFile.class);

	/**
	 * 添加忽略记录的参数类型
	 * @param clazz 参数类型
	 */
	public void addIgnoredParamClass(Class<?> clazz) {
		ignoredParamClasses.add(clazz);
	}

**Comment by Hccake** [comment]
#109
