### ISSUE TITLE
多数据源会支持吗？

### ISSUE THREAD

**Issue by nothingp** [ballcat-projects/ballcat#135]
公司原有模块是oracle，能不能系统管理这部分用mysql，然后提供多一个数据源连到oracle

**Comment by Hccake** [comment]
多数据源可以自行接入 sharding-jdbc 组件，或者 dynamic-datasource-starter 等组件。

但是如果没有必要的话，可以修改下 sql 脚本，系统管理也使用 oracle 数据库
