### ISSUE TITLE
ballcat-spring-boot-starter-swagger 包命名出错

### ISSUE THREAD

**Issue by KongZouXiang** [ballcat-projects/ballcat#166]
![000113713a08f4301fdd7cbd4ec93ec](https://user-images.githubusercontent.com/43474763/160168039-3adf8d3c-6ad0-4eac-b3a3-9b482d0e4073.png)

**Comment by Hccake** [comment]
starter 模块理论上应该拆分为两个包

common（功能） 和 starter（自动配置）

ballcat 中目前少量 starter 是进行了这样的拆分，如 redis、websocket、log

其余 starter 还没有拆分，所以现在还保留使用 common 的包名，也可以避免后续拆分时需要改动包名

**Comment by Hccake** [comment]
另外 `ballcat-spring-boot-starter-swagger` 已经不推荐使用了，建议使用 `ballcat-extend-openapi`，文档地址 http://www.ballcat.cn/guide/feature/openapi.html
