### ISSUE TITLE
模块扁平化处理

### ISSUE THREAD

**Issue by KongZouXiang** [ballcat-projects/ballcat#168]
![image](https://user-images.githubusercontent.com/43474763/160863876-68592864-2bb8-41d4-8997-4bfeaa98e45a.png)
模块层级导致看似公正有序，其实比较繁重，扁平化处理去除繁重，将模块全部改成一级，自动默认starter

**Comment by Hccake** [comment]
starter 中理论上只应存放自动配置类，目前的设计中不仅不应该合并，反而应该将未拆分的进行模块拆分。

拆分的好处：

1. 最小化依赖原则，只在启动类服务中进行 starter 的引用，其他共用模块中只引入对应的 common，可以避免依赖误传，在不需要一些 starter 的情况下，导致其自动配置
2. 方便定制化，用户可以自己根据 common 模块进行对应的 starter 的封装，方便业务开发时共享
