### ISSUE TITLE
文件上传优化

### ISSUE THREAD

**Issue by Hccake** [ballcat-projects/ballcat#171]
1. 文件上传的方法，上传后，返回的应该是 以 / 开头的，对应 root-path 的相对路径，方便用户自己补全文件的访问域名做反向代理。
目前返回了绝对路径，在 windows 环境下返回的路径类似于 D://xxx.pmg，这样用户是无法使用的。

2. 文件上传中的 Ftp 上传的方法可以考虑使用 hutool 中提供的工具，不用重复造轮子

3. 现有的  `FtpFileClient` 和 `LocalFileClient` 的部分方法是一样的，可以抽象一个 `AbstractFileClient`，它们两个继承这个抽象类

**Comment by JavaLionLi** [comment]
已完成
