### ISSUE TITLE
升级 SpringBoot 2.7.0，并调整自动配置类的注册方式

### ISSUE THREAD

**Issue by Hccake** [ballcat-projects/ballcat#184]
参看：https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-autoconfiguration-annotation

**Comment by zorohu** [comment]
@Hccake 升级依赖的话可以配置github的[Dependabot ](https://docs.github.com/cn/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)，更加方便的进行安全更新或依赖更新

**Comment by Hccake** [comment]
需要兼容低版本 springboot，spring.factories 暂时也需要保留
