### ISSUE TITLE
菜单配置

### ISSUE THREAD

**Issue by fengyuchenglun** [ballcat-projects/ballcat#220]
菜单配置配置略显繁琐与不便

**Comment by Hccake** [comment]
具体不便与繁琐在哪里？

**Comment by fengyuchenglun** [comment]
> 具体不便与繁琐在哪里？

菜单id没必要用户自己输入  就自动生成即可
虽然保证了菜单id有规律  甚至体现层级性

**Comment by Hccake** [comment]
等下周 1.0.0 版本发布后，只需要注释掉前端的菜单 ID 输入框，就可以支持使用自增的方式管理菜单 id 了
