### ISSUE TITLE
数据权限

### ISSUE THREAD

**Issue by fengyuchenglun** [ballcat-projects/ballcat#224]
系统管理角色配置的时候可以配置数据权限，但是无使用示例
我的理解是还需要自己定义datascope

**Comment by Hccake** [comment]
相关使用示例 在 ballcat-samples 仓库下: [CustomDataScope](https://github.com/ballcat-projects/ballcat-samples/blob/master/ballcat-sample-admin-application/src/main/java/com/your/packages/admin/datascope/CustomDataScope.java)
