### ISSUE TITLE
国际化 中 I18nField注解的 code也是支持Spel的吗,但是不生效

### ISSUE THREAD

**Issue by wuzhixaun** [ballcat-projects/ballcat#238]
求助求助

**Comment by Hccake** [comment]
支持的，你用的哪个版本？
另外最好可以给个可以复现的最简 demo，可以基于 https://github.com/ballcat-projects/ballcat-samples/blob/master/ballcat-sample-i18n 修改

**Comment by wuzhixaun** [comment]
`@Data
@I18nClass
public class TestData {
	@I18nField(code = "menu.order.xxx")
	private String username;
}`

我是要这样使用 code 国际化，然后报错 EL1008E: Property or field 'menu' cannot be found on object of type 'com.ecoflow.ecoflowexample.TestData' - maybe not public or not valid?

**Comment by Hccake** [comment]
menu 是 TestData 类的属性中吗，code 的 spel 解析时使用的当前对象内部的属性作为上下文

**Comment by wuzhixaun** [comment]
@Data @I18nClass public class TestData { @I18nField(code = "menu.order.xxx") private String username; 	private String code; }
那如果我取 TestData  中code 的值 ， @I18nField(code =spel ）这个spel应该怎么写了

**Comment by wuzhixaun** [comment]
可以了吧，直接写字段名就好了，多谢大佬

**Comment by Hccake** [comment]
不客气，解决了就好
