### ISSUE TITLE
国际化反射翻译设置值出现性能问题，这个有思路吗

### ISSUE THREAD

**Issue by wuzhixaun** [ballcat-projects/ballcat#244]
通常一个列表接口只需要89ms 但是加上国际化2-3s了

**Comment by Hccake** [comment]
反射影响不会有这么大的，参看预览地址的菜单列表接口，加上国际化也就是几十ms的响应时间。

你需要检查的是你的 I18nMessageProvider 或者自定义的 MessageResource，是否没有使用缓存，频繁的查询数据库。

**Comment by wuzhixaun** [comment]
走的是redis缓存，但是接口是 R<List<Menu>>

**Comment by Hccake** [comment]
github 上开一个最简的复现 demo，我测试下

**Comment by wuzhixaun** [comment]
仔细检查了一下，确实是自定义I18nMessageProvider 这边有问题，redis这边使用不当，导致每次存进去的value都序列化为二进制然后取出来又需要转，优化了这块逻辑就不会有问题了

**Comment by Hccake** [comment]
done
