### ISSUE TITLE
有一些mapper的xml为什么找不到呀

### ISSUE THREAD

**Issue by kangxiaolan** [ballcat-projects/ballcat#245]
比如说system中的模块,只看到了五个mapper的xml文件还有其他的 ，例如sysConfigMapper.xml就找不到

**Comment by lingting** [comment]
因为它没有用到xml文件，就没建



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月27日(周一) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ballcat-projects/ballcat] 有一些mapper的xml为什么找不到呀 (Issue #245)




 
比如说system中的模块,只看到了五个mapper的xml文件还有其他的 ，例如sysConfigMapper.xml就找不到

**Comment by kangxiaolan** [comment]
先感谢一下回答，但是我现在引入system这个模块的时候，sysConfigMapper这个接口就会因为没有实现类创建失败，猜测是不是因为没有xml的原因

**Comment by lingting** [comment]
> 先感谢一下回答，但是我现在引入system这个模块的时候，sysConfigMapper这个接口就会因为没有实现类创建失败，猜测是不是因为没有xml的原因

建议贴出你的报错信息, 或者 尝试在启动类添加 @MapperScan("com.hccake.ballcat.*.mapper")
