### ISSUE TITLE
页面缓存失败，切换tabs标签页时，页面接口重复请求2次

### ISSUE THREAD

**Issue by amychuchu** [ballcat-projects/ballcat#249]
页面缓存失败，切换tabs标签页时，页面接口重复请求2次，每次切换都会请求缓存没有效果

**Comment by amychuchu** [comment]
是用react开发的那套demo

**Comment by Hccake** [comment]
> 是用react开发的那套demo

确认是 bug，会进行修复。
另外建议相关问题到对应的代码仓库去提

**Comment by lingting** [comment]
https://github.com/ballcat-projects/ballcat-ui-react/commit/b9c4d6800c049bdb0328062c9f7bb041a923d5a2
