### ISSUE TITLE
数据库脚本在mysql 5.7.30 执行错误

### ISSUE THREAD

**Issue by fengyuchenglun** [ballcat-projects/ballcat#257]
oauth2_authorization
oauth2_authorization_consent
oauth2_registered_client
相关的几个表  主要是timestamp的默认值，比如
 client_secret_expires_at timestamp default null 需修改成  client_secret_expires_at timestamp null

**Comment by Hccake** [comment]
对于 mysql 5.7.x 系列，可以先执行以下 SQL，以便支持 timestamp 列的默认值为 null
```SQL
set session explicit_defaults_for_timestamp = 1;
```
然后再执行 oauth2 相关表的创建。

或者直接升级 mysql 8.x。
