### ISSUE TITLE
SAS授权码模式login page无法正确显示

### ISSUE THREAD

**Issue by evil0th** [ballcat-projects/ballcat#318]
form-login:login-page 返回404

**Comment by Hccake** [comment]
spring 默认的 formlogin 在使用了自定义的 AuthenticationEntryPoint 后，将不会进行对应拦截器的注册，暂时取消了组件内部默认注册 AuthenticationEntryPoint 的操作，决定权交由业务自由控制。

![image](https://github.com/user-attachments/assets/ffcd44d5-01e2-47e9-a831-270e3b039ac5)

**Comment by Hccake** [comment]
如果需要同时控制 AuthenticationEntryPoint ，可以复制 DefaultLoginPageConfigurer 并调整判断逻辑，然后自定义一个 SpringSecurityConfigurerCustomizer 注册该 Configurer

**Comment by evil0th** [comment]
感谢感谢！
