### ISSUE TITLE
项目是未完全开源吗？

### ISSUE THREAD

**Issue by jaaaar** [ballcat-projects/ballcat#91]
现在的代码无法通过build啊，HeadMeta这个类没有

**Comment by Hccake** [comment]
@jaaaar  项目是完全开源的。

之前Excel 一部分代码漏提交了，现在已经合并最新，可以重新拉取下代码了。

目前 master 分支是开发中的 0.1.0 版本，想要稳定版可以对应之前的各个版本 tag 进行检出。
